### ISSUE TITLE
Add Error Handling

### ISSUE THREAD

**Issue by vidhvath28** [102/belgrade-weather#3]
Lack of Robust Error Handling: The script may fail if the JSON file is missing, incorrectly formatted, or does not contain the expected data structure. Implementing proper error handling will improve stability and user experience.

**Comment by vidhvath28** [comment]
@102  I would like to work on this issue, kindly assign this issue to me

**Comment by vidhvath28** [comment]
@102  I have resolved this issue and submitted a PR  #7

**Comment by 102** [comment]
Hey @vidhvath28 thanks for the proposals! However, I can't see added value in these suggestions
