### ISSUE TITLE
Documentation and User Experience

### ISSUE THREAD

**Issue by vidhvath28** [102/belgrade-weather#4]
Insufficient Documentation: The lack of clear instructions on how to use the project or its limitations may hinder user engagement. Providing comprehensive documentation will help users understand and effectively utilize the project.

**Comment by vidhvath28** [comment]
@102  I would like to work on this issue, kindly assign this issue to me

**Comment by 102** [comment]
Hey @vidhvath28 thanks for the proposals! However, I can't see added value in these suggestions
