### ISSUE TITLE
Data Consistency and Quality

### ISSUE THREAD

**Issue by vidhvath28** [102/belgrade-weather#5]
Inconsistent Updates: The historical weather data may not be updated regularly, leading to gaps or outdated information that could misrepresent current trends.
Missing Values: Records may contain missing or incomplete data, which can affect the reliability of any analyses or insights derived from the dataset.

**Comment by vidhvath28** [comment]
worked on this issue and submitted  a PR #8.

**Comment by 102** [comment]
Hey @vidhvath28 thanks for the proposals! However, I can't see added value in these suggestions
